### PR TITLE
Non-empty hearts and more options

### PR DESCRIPTION
**Pull request by IonicaBizau**
Added new options:
- `fill` (String): To specify the character to fill the heart with (default: space). See the example.
- `trim` (Boolean): If `false`, the trailing spaces on the right side will _not_ be removed (default: `true`). It is handy when we have ASCII animations (so the width/height remain the same).

Moved the other arguments in the options (breaking change, so I bumped the major version tag). :boom:

### CODE REVIEW

**Comment by nuvipannu** [comment]
😍💗👍🏼 Wow!!! This is amazing. Love the fill option. Can't wait to use it with animations 😍🤗 Thank you Johnny B! I love it :)

**Comment by IonicaBizau** [comment]
@nuvipannu You deserve it! :+1: :joy:

**Comment by IonicaBizau** [comment]
@nuvipannu I have just `npm publish`ed the new version on npm. :rocket:

**Comment by nuvipannu** [comment]
Woooo! :heart:

That's awesome of you to do that :) Thanks Johnny! I watched the Back to
the Future movie over the weekend and that song Go Johnny, Go, Go, Go!
Johnny B Good! song came on when they were at the dance and I smiled and
thought of you :)

So someone asked this question today (see screenshot image) and I tried to
look through your repo's to give this guy a link to the github
contributions calendar package you made to make the I LOVE GITHUB calendar
like that. What was the name of it again?

I am applying to jobs on this website: https://weworkremotely.com/

I really like the break that I have had recently since quitting work. I
really feel that I needed it. I want to get back to working now, but fully
remotely. I am going to do that Front End Developer test sometime this week
to make my profile more competitive for jobs at this website (for tech jobs
for women): https://www.powertofly.com/

So I was wondering if maybe some time this week we can do a session for
like one hour while I am doing the test from HackerRank and we connect on
Google Remote Desktop. I will do the answers to the best of my abilities
and after doing some Google searching, but if I cannot figure it out, can
you back me up and help me answer them? I think I will need more help on
the Javascript related questions. You are a Javascript expert ninja :D

Much Love,
Nuvi <3

**Pull request merged**
